### ISSUE TITLE
Images don't display

### ISSUE THREAD

**Issue by clawoflight** [bibletime/bibletime#95]
Hello,
Images are not rendered.

I tried this with several of the map modules (HistMidEast, SmithBibleAtlas, etc.).
The descriptions are rendered properly, but without the images.
Additionally and possibly related, bibletime segfaults when closing a module with images.

Relevant debug output:
```
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Not allowed to load local resource: file:///home/bennett/.sword/modules/genbook/rawgenbook/smithatlas/images/bibleatlas01stitlepg.jpg"
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Not allowed to load local resource: file:///home/bennett/.sword/modules/genbook/rawgenbook/smithatlas/images/bibleatlas02segypt1450bc.jpg"
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Not allowed to load local resource: file:///home/bennett/.sword/modules/genbook/rawgenbook/smithatlas/images/bibleatlas03sbabylon560bc.jpg"
```
I also have the backtrace from the coredump, but only without debug symbols:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `bibletime --debug'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f827a99047f in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
[Current thread is 1 (Thread 0x7f8281dfb8c0 (LWP 10355))]
>>> bt
#0  0x00007f827a99047f in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#1  0x00007f827a990929 in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#2  0x00007f8279c95411 in QObjectPrivate::deleteChildren() () from /usr/lib/libQt5Core.so.5
#3  0x00007f827a99063b in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#4  0x00007f827aab4019 in QMdiSubWindow::~QMdiSubWindow() () from /usr/lib/libQt5Widgets.so.5
#5  0x00007f8279c97be0 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#6  0x00007f827a994ecb in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#7  0x00007f827aab48cb in QMdiSubWindow::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007f827a94d34c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007f827a954b61 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007f8279c6b440 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#11 0x00007f8279c6dbcd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#12 0x00007f8277b0b584 in ?? () from /usr/lib/libQt5Quick.so.5
#13 0x00007f8277b0b800 in QQuickRenderControl::~QQuickRenderControl() () from /usr/lib/libQt5Quick.so.5
#14 0x00007f8277303383 in ?? () from /usr/lib/libQt5QuickWidgets.so.5
#15 0x00007f8277301fd3 in ?? () from /usr/lib/libQt5QuickWidgets.so.5
#16 0x00007f8277302059 in ?? () from /usr/lib/libQt5QuickWidgets.so.5
#17 0x00007f8279c9edb7 in QObject::~QObject() () from /usr/lib/libQt5Core.so.5
#18 0x00007f827a9906b3 in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#19 0x00007f8281168b4a in ?? () from /usr/lib/libQt5WebEngineWidgets.so.5
#20 0x00007f827b916adb in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#21 0x00007f827b916c69 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#22 0x00007f827c10075f in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#23 0x00007f827c0f3683 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#24 0x00007f827c29641e in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#25 0x00007f827c06fccd in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#26 0x00007f827c070169 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#27 0x00007f827c07635d in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#28 0x00007f827c298aeb in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#29 0x00007f827c29431a in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#30 0x00007f827c1952b4 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#31 0x00007f827c195639 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#32 0x00007f827b9336ce in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#33 0x00007f827b93392a in QtWebEngineCore::WebContentsAdapter::~WebContentsAdapter() () from /usr/lib/libQt5WebEngineCore.so.5
#34 0x00007f828115abc6 in ?? () from /usr/lib/libQt5WebEngineWidgets.so.5
#35 0x00007f828115abd9 in ?? () from /usr/lib/libQt5WebEngineWidgets.so.5
#36 0x00007f8281155310 in QWebEnginePage::~QWebEnginePage() () from /usr/lib/libQt5WebEngineWidgets.so.5
#37 0x00000000005336e9 in BtHtmlReadDisplay::~BtHtmlReadDisplay() ()
#38 0x00007f8281164caa in ?? () from /usr/lib/libQt5WebEngineWidgets.so.5
#39 0x00000000005343c3 in BtHtmlReadDisplayView::~BtHtmlReadDisplayView() ()
#40 0x0000000000534409 in BtHtmlReadDisplayView::~BtHtmlReadDisplayView() ()
#41 0x00007f8279c95411 in QObjectPrivate::deleteChildren() () from /usr/lib/libQt5Core.so.5
#42 0x00007f827a99063b in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#43 0x00007f827aadd379 in QSplitter::~QSplitter() () from /usr/lib/libQt5Widgets.so.5
#44 0x00007f8279c95411 in QObjectPrivate::deleteChildren() () from /usr/lib/libQt5Core.so.5
#45 0x00007f827a99063b in QWidget::~QWidget() () from /usr/lib/libQt5Widgets.so.5
#46 0x0000000000566a21 in CBookReadWindow::~CBookReadWindow() ()
#47 0x00007f8279c97be0 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#48 0x00007f827a994ecb in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#49 0x00007f827aa93d0b in QMainWindow::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#50 0x00007f827a94d34c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#51 0x00007f827a954b61 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#52 0x00007f8279c6b440 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#53 0x00007f8279c6dbcd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#54 0x00007f8279cbfc43 in ?? () from /usr/lib/libQt5Core.so.5
#55 0x00007f82769e1587 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#56 0x00007f82769e17f0 in ?? () from /usr/lib/libglib-2.0.so.0
#57 0x00007f82769e189c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#58 0x00007f8279cc004f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#59 0x00007f8279c6989a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#60 0x00007f8279c71de4 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#61 0x000000000049f1f5 in main ()
```

Version: 2.11 (on Arch Linux, but a friend has the same problem on Windows 7)

My C++ is basic, but I'm a CompSci student and fluent in many other things, so I can probably help debug this.

**Comment by jaakristioja** [comment]
I can confirm the images not displaying, but not yet the crash.

**Comment by gholmlund** [comment]
The crash is bug #94 which has already been fixed and is not related to the image problem.

**Comment by gholmlund** [comment]
The display of images was a security issue. More detail are in this Qt bug report.
https://bugreports.qt.io/browse/QTBUG-55902

**Comment by clawoflight** [comment]
Well, that was fast. Thanks a lot! :)
